# This file was generated by GoReleaser. DO NOT EDIT.
cask "handinger" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "33b51195863c527f07515f14d771e1b9212f6eb5af993d8010876f13ef251052"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "3b4cb91093b34b18d26c0c8eeb9cdbe583e8f82bbf862e32ac042115f7cf8f86"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "678aee087ba95f1b2fccb95e9d91fdda15f2e6659a3a2f0e816d9c00d761e7ce"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4269b48616ecb5e66fe369d27c308683dac2d13ea3295860ceee729bfe130d3b"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_linux_arm64.tar.gz"
    end
  end

  name "handinger"
  desc "The official CLI for Handinger."
  homepage "https://handinger.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "handinger"
  manpage "man/man1/handinger.1.gz"
  bash_completion "completions/handinger.bash"
  fish_completion "completions/handinger.fish"
  zsh_completion "completions/handinger.zsh"

  # No zap stanza required

end
