# This file was generated by GoReleaser. DO NOT EDIT.
cask "handinger" do
  version "0.11.1"

  on_macos do
    on_intel do
      sha256 "67dba1a5de2b1b8aedd9784506c7a63569036809f6a46349f955d6a9ce19bf5c"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "464d3c4e97e18202738e9828f366e55a91158f413f812b2754a038e02c9c95ca"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "9326727eb43843a9920edc7c2e766046d9858dbc659c59f773679af755010324"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f33bd4398f8591c44115a8803c24af8ae33020c69a9d8ee4941eefb3b180ca1"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_linux_arm64.tar.gz"
    end
  end

  name "handinger"
  desc "The official CLI for Handinger."
  homepage "https://handinger.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "handinger"
  manpage "man/man1/handinger.1.gz"
  bash_completion "completions/handinger.bash"
  fish_completion "completions/handinger.fish"
  zsh_completion "completions/handinger.zsh"

  # No zap stanza required

end
