# This file was generated by GoReleaser. DO NOT EDIT.
cask "handinger" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "899406b30e1320074dd724971743aa2c2e927e5879d76e9db959021e5ac7d7f1"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "094a1f7de79ed80eab858129e8370ebbac6232c5e8e3f06e9d5007c672cf1121"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "eb2873777fde68c0aa6f8e859612aad116f6f67fbf7c680118970c98474ac44c"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "41fb937e33c98785a774c9f298bdee5c81ba575dd14d3a02f3b003e7ca49650d"
      url "https://github.com/ramensoft/handinger-cli/releases/download/v#{version}/handinger_#{version}_linux_arm64.tar.gz"
    end
  end

  name "handinger"
  desc "The official CLI for Handinger."
  homepage "https://handinger.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "handinger"
  manpage "man/man1/handinger.1.gz"
  bash_completion "completions/handinger.bash"
  fish_completion "completions/handinger.fish"
  zsh_completion "completions/handinger.zsh"

  # No zap stanza required

end
